### ISSUE TITLE
Document the OpenShift environment defaults that ODH requires for a successful deployment

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/opendatahub.io#68]
We need to provide the OCP cluster environmental defaults that ODH currently depends on for a successful. 

- Minimum cluster size: Worker nodes CPU/Memory
- Internal Registry requirement
- Default `storageClass` defined
- Anything else that is required

**Comment by dmarcus-wire** [comment]
Minimum Cluster Size should be bumped up from this in order to handle the largest ODH notebook image sizes: https://www.redhat.com/en/resources/self-managed-openshift-sizing-subscription-guide#section-4. If not, the spawn crashes and you have to go smaller (lame). see next item.

The default MachineSet specification should be left as is and a secondary MachineSet should be defined with Autoscaling for a better IT and Dev experience. See https://developers.redhat.com/articles/2023/01/12/how-autoscale-saas-application-infrastructure#kubernetes_native_infrastructure

Internal Registry we should reference making sure its configured https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/registry/registry-overview#registry-integrated-openshift-registry_registry-overview. Even with a working cluster, if the image registry is not properly configured you can spawn a notebook, but it will fail when trying to attached the notebook image stream to the container.

Persistent storage and storageclass operational for persistence https://developers.redhat.com/blog/2020/10/22/persistent-storage-in-action-understanding-red-hat-openshifts-persistent-volume-framework#persistent_storage_types

Cluster admin permissions
